/**
 * Live 遊戲指定點擊串聯到第三方遊戲大廳
 * Key format: {Vendor}_{gateway}
 */
export const LiveGameLaunchMap = {
  PP_1: { vendor_code: 'PP', game_code: 'PP_104' },
  MG_1: { vendor_code: 'MG', game_code: 'MG_MGL_GRAND_LobbyAll' },
  EZUGI_1: { vendor_code: 'EZUGI', game_code: 'EZUGI_baccarat' },
  WIFY_1: { vendor_code: 'WIFY', game_code: 'WIFY_Lobby' },
  YB_1: { vendor_code: 'YB', game_code: 'YB_Lobby' },
  AA_1: { vendor_code: 'AA', game_code: 'AA_MX-LIVE-017' },
  GPK7MJ_1: { vendor_code: 'GPK7MJ', game_code: 'GPK7MJ_Lobby' },
  GPKICONIC_1: { vendor_code: 'GPKICONIC', game_code: 'GPKICONIC_launch_prime_bj_3' },
  DG_1: { vendor_code: 'DG', game_code: 'DG_21401' },
  PT_1: { vendor_code: 'PT', game_code: 'PT_ag_baccarat' },
  WMLIVE_1: { vendor_code: 'WMLIVE', game_code: 'WMLIVE_101' },
  WCLIVE_1: { vendor_code: 'WCLIVE', game_code: 'WCLIVE_0' },
  AMUSNET_1: { vendor_code: 'AMUSNET', game_code: 'AMUSNET_3104' },
  CQ9_1: { vendor_code: 'CQ9', game_code: 'CQ9_GINKGO03' },
  PP_2: { "vendor_code": "PP", "game_code": "101" },
  MG_2: { "vendor_code": "MG", "game_code": "SMG_MGLiveGrand_Baccarat5" },
  Evolution_2: { "vendor_code": "Evolution", "game_code": "8clwnwrupuvf0osq" },
  HB_2: { "vendor_code": "HB", "game_code": "SicBo" },
  DreamGame_2: { "vendor_code": "DreamGame", "game_code": "lobby" },
  EZUGI_2: { "vendor_code": "EZUGI", "game_code": "-99" },
  Skywind_2: { "vendor_code": "Skywind", "game_code": "sw_ro_jw" },
  Wazdan_2: { "vendor_code": "Wazdan", "game_code": "1286" },
  RelaxGaming_2: { "vendor_code": "RelaxGaming", "game_code": "150186" },
  VivoGaming_2: { "vendor_code": "VivoGaming", "game_code": "lobby" },
  TGSpeed_2: { "vendor_code": "TGSpeed", "game_code": "speed" },
  GameArt_2: { "vendor_code": "GameArt", "game_code": "321" },
  BlueprintGaming_2: { "vendor_code": "BlueprintGaming", "game_code": "BPG-qtechblackjack" },
  BetGamesTv_2: { "vendor_code": "BetGamesTv", "game_code": "-1" },
  Dowinn_2: { "vendor_code": "Dowinn", "game_code": "dowinn" },
  Playtech_2: { "vendor_code": "Playtech", "game_code": "3brgl" },
  SAGaming_2: { "vendor_code": "SAGaming", "game_code": "908" },
  SexyCasino_2: { "vendor_code": "SexyCasino", "game_code": "MX-LIVE-001" },
  CockFight_2: { "vendor_code": "CockFight", "game_code": "SV-LIVE-001" },
  HotRoad_2: { "vendor_code": "HotRoad", "game_code": "HOTROAD-LIVE-001" },
  AllbetLive_2: { "vendor_code": "AllbetLive", "game_code": "101" },
  OrientalGaming_2: { "vendor_code": "OrientalGaming", "game_code": "1" },
  XproGaming_2: { "vendor_code": "XproGaming", "game_code": "1" },
  BigGaming_2: { "vendor_code": "BigGaming", "game_code": "1" },
  WIFY_2: { "vendor_code": "WIFY", "game_code": "6215f8a7fa722ee92d18855b" },
  PrettyGaming_2: { "vendor_code": "PrettyGaming", "game_code": "4Point" },
  CPGames_2: { "vendor_code": "CPGames", "game_code": "2_1700015" },
  HoGaming_2: { "vendor_code": "HoGaming", "game_code": "bac10n4j02hn1m09" },
  Choice_2: { "vendor_code": "Choice", "game_code": "0" }
}